[custom]
;手机可以选择哪些APP是否代理，此时的规则可以根据包名进行分流，只需要分流哪些APP走哪个代理
ruleset=🥫 Instagram,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_instagram.list
ruleset=⚛️ OpenAi,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_openai.list
ruleset=🌐 Edge,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_edge.list
ruleset=🦊 Firefox,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_firefox.list
ruleset=⏩ SpeedTest,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_speedtest.list
ruleset=💻 VMOS,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_vmos.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_all.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/rule/ProxyAI.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/rule/ProxyMedia.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/rule/ProxyLite.list
ruleset=🐟 全部匹配,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]REJECT`.*
;按顺序依次添加包含关键字的节点，如果使用小括号，不一定保证顺序
custom_proxy_group=🥫 Instagram`select`[]REJECT`Zgo`DMIT`US
custom_proxy_group=⚛️ OpenAi`select`[]REJECT`(Zgo|DMIT|US)
custom_proxy_group=🌐 Edge`select`[]REJECT`.*`[]DIRECT
custom_proxy_group=🦊 Firefox`select`[]REJECT`.*`[]DIRECT
custom_proxy_group=⏩ SpeedTest`select`[]REJECT`.*`[]DIRECT
custom_proxy_group=💻 VMOS`select`[]REJECT`.*`[]DIRECT
custom_proxy_group=🔛 前置节点`select`[]REJECT`.*`[]DIRECT
custom_proxy_group=🐟 全部匹配`select`[]🚀 节点选择

enable_rule_generator=true
overwrite_original_rules=true
