[custom]
;手机可以选择哪些APP是否代理，此时的规则可以根据包名进行分流，只需要分流哪些APP走哪个代理
ruleset=⚛️ OpenAi,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_openai.list
ruleset=🐟 全部匹配,https://raw.githubusercontent.com/ixxc/ixxc/main/clash/mobile_all.list
ruleset=🐟 全部匹配,[]FINAL

custom_proxy_group=🚀 节点选择`select`.*
custom_proxy_group=🔮 负载均衡`load-balance`(广港IEPL)`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=⚛️ OpenAi`select`(US)
custom_proxy_group=🐟 全部匹配`select`[]🔮 负载均衡`[]🚀 节点选择

enable_rule_generator=true
overwrite_original_rules=true
